version: '3.8'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes: 
      - metabase-data:/metabase-data
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: logistics_db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: password
      MB_DB_HOST: postgres
      MB_SITE_URL: http://localhost:3001
    networks:
      - default
    depends_on:
      - postgres
    restart: always

volumes:
  metabase-data:

networks:
  default:
    external:
      name: fullstack-ai-dashboard_logistics_network
